# SPDX-License-Identifier: WTFPL
name: Feature request
description: Suggest an improvement
labels: [enhancement]
body:
  - type: textarea
    id: idea
    attributes:
      label: Proposal
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Context
